version: '3'
services:

  application:
    build:
      context: ./
      dockerfile: images/application/Dockerfile
    entrypoint: /entrypoint.local.sh
    depends_on:
      - mysql
    environment:
      - APPLICATION_HOSTNAME=${APPLICATION_HOSTNAME}
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
    volumes:
      - ../:/app:delegated

  workspace:
    build:
      context: ./
      dockerfile: images/workspace/Dockerfile
    depends_on:
      - mysql
    environment:
      - APPLICATION_HOSTNAME=${APPLICATION_HOSTNAME}
      - ENVIRONMENT=local
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
    volumes:
      - ../:/app:delegated
      - ./images/workspace/root/etc/confd:/etc/confd
      - ./images/workspace/root/home/build/bin:/home/build/bin
      - ./config:/config

  mysql:
    image: mysql:5.7
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USERNAME}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}

  redis:
    image: redis:4-alpine
